image: node:16.5.0

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

pages:
  script:
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    - . "$HOME/.cargo/env"
    - rustup update
    - rustup target add wasm32-unknown-unknown
    - cargo install wasm-pack
    - rustup component add rust-src
    - cd tsunami
    - npm run build
    - mkdir -p public
    - cp -r dist/* public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
