image: node:16.5.0

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

pages:
  script:
    - apt install rustup
    - rustup update
    - rustup target add wasm32-unknown-unknown
    - cd tsunami
    - npm run build
    - mkdir -p public
    - cp -r dist/* public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
