[package]
edition = "2021"
name = "flow"
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]
name = "flow"

[dependencies]
klu-rs = "0.4"
nalgebra = "0.32"
ndarray = {version = "0.15", features = ["approx-0_5"]}
ndarray-linalg = {version = "0.16", features = ["openblas-system"]}
num-traits = "0.2"
numpy = "0.19"
pyo3 = {version = "0.19", features = ["extension-module"]}
sprs = "0.11"
strum = "0.25"
strum_macros = "0.25"

[dev-dependencies]
approx = "0.5"

[profile.release]
debug = true
lto = "thin"
