[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-undefined", "-C", "link-arg=dynamic_lookup"]

[target.wasm32-unknown-unknown]
rustflags = ["-C", "target-feature=+atomics,+bulk-memory,+mutable-globals"]

[env]
PYO3_PYTHON = "/usr/local/bin/python3"

[unstable]
build-std = ["panic_abort", "std"]
